import json
import os
import sys

if hasattr(sys.stdout, 'reconfigure'):
    sys.stdout.reconfigure(encoding='utf-8')
if hasattr(sys.stderr, 'reconfigure'):
    sys.stderr.reconfigure(encoding='utf-8')

def create_demo_notebook():
    notebook = {
        "cells": [
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "# TOPIC 4: STOCK PRICE FORECASTING (DỰ BÁO GIÁ CỔ PHIẾU)\n",
                    "## BÁO CÁO NGHIÊN CỨU & DEMO HỆ THỐNG ĐỊNH LƯỢNG VỚI DEEP LEARNING\n",
                    "---\n",
                    "### 📌 Đáp ứng 100% yêu cầu đề tài (docs/Topic.png):\n",
                    "1. **Task**: Regression (Hồi quy giá cổ phiếu).\n",
                    "2. **Dataset**: Yahoo Finance (`yfinance`).\n",
                    "3. **Core Model**: LSTM for Regression (Vanilla LSTM & Deep LSTM).\n",
                    "4. **Extension 1**: Compare CNN vs. LSTM (So sánh toàn diện CNN 1D vs. LSTM).\n",
                    "5. **Extension 2**: Add multi-step forecasting (Dự báo đa bước 7 ngày với Seq2Seq).\n",
                    "6. **Điểm sáng NCKH (SOTA)**: Đề xuất mô hình lai **CNN-BiLSTM-Self-Attention** kết hợp **Directional Penalty Loss** & **Financial Backtest** (Sharpe, Drawdown có trừ phí sàn).\n",
                    "\n",
                    "---"
                ]
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "## PHẦN 1: KHỞI TẠO MÔI TRƯỜNG & IMPORT THƯ VIỆN"
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "import os\n",
                    "import sys\n",
                    "import yaml\n",
                    "import numpy as np\n",
                    "import pandas as pd\n",
                    "import matplotlib.pyplot as plt\n",
                    "import seaborn as sns\n",
                    "import yfinance as yf\n",
                    "import torch\n",
                    "import torch.nn as nn\n",
                    "from torch.utils.data import Dataset, DataLoader\n",
                    "from sklearn.preprocessing import RobustScaler, MinMaxScaler\n",
                    "\n",
                    "# Thiết lập hiển thị đồ thị đẹp mắt\n",
                    "plt.style.use('seaborn-v0_8-whitegrid' if 'seaborn-v0_8-whitegrid' in plt.style.available else 'default')\n",
                    "plt.rcParams['figure.figsize'] = (12, 6)\n",
                    "plt.rcParams['font.size'] = 11\n",
                    "device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
                    "print(f\"[Môi trường] Thiết bị tính toán: {device} | PyTorch: {torch.__version__}\")"
                ]
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "## PHẦN 2: TẢI DỮ LIỆU YAHOO FINANCE & PHÂN TÍCH KHÁM PHÁ (EDA)\n",
                    "Tải dữ liệu cổ phiếu mục tiêu (`AAPL`) cùng các chỉ số vĩ mô liên thị trường (`^VIX` - Đo lường rủi ro & `^TNX` - Lợi suất Trái phiếu Chính phủ Mỹ 10 năm)."
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "ticker = 'AAPL'\n",
                    "start_date = '2018-01-01'\n",
                    "end_date = '2024-12-31'\n",
                    "\n",
                    "print(f\"[Data] Đang tải dữ liệu {ticker} từ Yahoo Finance ({start_date} -> {end_date})...\")\n",
                    "df_raw = yf.download(ticker, start=start_date, end=end_date, progress=False)\n",
                    "if isinstance(df_raw.columns, pd.MultiIndex):\n",
                    "    df_raw.columns = df_raw.columns.get_level_values(0)\n",
                    "df_raw.reset_index(inplace=True)\n",
                    "df_raw['Date'] = pd.to_datetime(df_raw['Date'])\n",
                    "df_raw = df_raw.dropna().sort_values('Date').reset_index(drop=True)\n",
                    "\n",
                    "print(f\"[Data] Tổng số phiên giao dịch: {len(df_raw)}\")\n",
                    "display(df_raw.head())\n",
                    "\n",
                    "# Trực quan hóa giá đóng cửa AAPL\n",
                    "plt.figure(figsize=(14, 5))\n",
                    "plt.plot(df_raw['Date'], df_raw['Close'], label='AAPL Close Price ($)', color='#1f77b4', lw=1.8)\n",
                    "plt.title(f'Lịch Sử Giá Đóng Cửa {ticker} (Yahoo Finance: {start_date} -> {end_date})', fontsize=14, fontweight='bold')\n",
                    "plt.xlabel('Thời gian')\n",
                    "plt.ylabel('Giá ($)')\n",
                    "plt.legend(loc='upper left')\n",
                    "plt.tight_layout()\n",
                    "plt.show()"
                ]
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "## PHẦN 3: KỸ THUẬT ĐẶC TRƯNG & CHỐNG RÒ RỈ DỮ LIỆU (ZERO DATA LEAKAGE)\n",
                    "Trích xuất 20+ chỉ báo kỹ thuật (RSI, MACD, Bollinger Bands, ATR, OBV) và phân chia Train (70%) / Val (15%) / Test (15%). Scaler chỉ được fit trên tập Train."
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "def add_technical_indicators(df):\n",
                    "    d = df.copy()\n",
                    "    # EMA\n",
                    "    for span in [9, 21, 50, 200]:\n",
                    "        d[f'EMA_{span}'] = d['Close'].ewm(span=span, adjust=False).mean()\n",
                    "    # RSI\n",
                    "    delta = d['Close'].diff()\n",
                    "    gain = delta.clip(lower=0)\n",
                    "    loss = -delta.clip(upper=0)\n",
                    "    avg_gain = gain.rolling(14).mean()\n",
                    "    avg_loss = loss.rolling(14).mean()\n",
                    "    rs = avg_gain / (avg_loss + 1e-9)\n",
                    "    d['RSI_14'] = 100 - (100 / (1 + rs))\n",
                    "    # MACD\n",
                    "    ema12 = d['Close'].ewm(span=12, adjust=False).mean()\n",
                    "    ema26 = d['Close'].ewm(span=26, adjust=False).mean()\n",
                    "    d['MACD'] = ema12 - ema26\n",
                    "    d['MACD_Signal'] = d['MACD'].ewm(span=9, adjust=False).mean()\n",
                    "    d['MACD_Hist'] = d['MACD'] - d['MACD_Signal']\n",
                    "    # Bollinger Bands\n",
                    "    sma20 = d['Close'].rolling(20).mean()\n",
                    "    std20 = d['Close'].rolling(20).std()\n",
                    "    d['BB_Upper'] = sma20 + 2 * std20\n",
                    "    d['BB_Lower'] = sma20 - 2 * std20\n",
                    "    d['BB_Width'] = (d['BB_Upper'] - d['BB_Lower']) / (sma20 + 1e-9)\n",
                    "    d['BB_PctB'] = (d['Close'] - d['BB_Lower']) / (d['BB_Upper'] - d['BB_Lower'] + 1e-9)\n",
                    "    # ATR\n",
                    "    tr = pd.concat([\n",
                    "        d['High'] - d['Low'],\n",
                    "        (d['High'] - d['Close'].shift()).abs(),\n",
                    "        (d['Low'] - d['Close'].shift()).abs()\n",
                    "    ], axis=1).max(axis=1)\n",
                    "    d['ATR_14'] = tr.rolling(14).mean()\n",
                    "    # OBV\n",
                    "    direction = np.where(d['Close'] > d['Close'].shift(), 1, np.where(d['Close'] < d['Close'].shift(), -1, 0))\n",
                    "    d['OBV'] = (direction * d['Volume']).cumsum()\n",
                    "    # Returns\n",
                    "    d['Log_Ret_1d'] = np.log(d['Close'] / d['Close'].shift(1))\n",
                    "    d['Log_Ret_5d'] = np.log(d['Close'] / d['Close'].shift(5))\n",
                    "    d['Log_Ret_20d'] = np.log(d['Close'] / d['Close'].shift(20))\n",
                    "    return d.dropna().reset_index(drop=True)\n",
                    "\n",
                    "df_features = add_technical_indicators(df_raw)\n",
                    "feature_cols = [c for c in df_features.columns if c not in ['Date']]\n",
                    "print(f\"[Pipeline] Trích xuất thành công {len(feature_cols)} đặc trưng đầu vào!\")\n",
                    "\n",
                    "# Phân chia Train/Val/Test tuần tự theo thời gian (70% / 15% / 15%)\n",
                    "n = len(df_features)\n",
                    "train_end = int(n * 0.70)\n",
                    "val_end = int(n * 0.85)\n",
                    "\n",
                    "df_train = df_features.iloc[:train_end].copy()\n",
                    "df_val = df_features.iloc[train_end:val_end].copy()\n",
                    "df_test = df_features.iloc[val_end:].copy()\n",
                    "\n",
                    "# Chuẩn hóa: Fit Scaler CHỈ TRÊN TẬP TRAIN (Zero Data Leakage)\n",
                    "scaler = RobustScaler()\n",
                    "train_scaled = scaler.fit_transform(df_train[feature_cols])\n",
                    "val_scaled = scaler.transform(df_val[feature_cols])\n",
                    "test_scaled = scaler.transform(df_test[feature_cols])\n",
                    "\n",
                    "print(f\"[Split] Train: {len(df_train)} | Val: {len(df_val)} | Test: {len(df_test)}\")"
                ]
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "## PHẦN 4: TẠO SLIDING WINDOW DATASET CHO PYTORCH\n",
                    "Tạo cửa sổ trượt $L=60$ ngày lịch sử để dự báo giá Close ngày $t+1$ (Single-step) và $t+1 \\dots t+7$ (Multi-step)."
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "class StockWindowDataset(Dataset):\n",
                    "    def __init__(self, data_array, window_size=60, horizon=1, target_col_idx=3):\n",
                    "        self.window_size = window_size\n",
                    "        self.horizon = horizon\n",
                    "        self.target_col_idx = target_col_idx\n",
                    "        self.X, self.y = [], []\n",
                    "        for i in range(len(data_array) - window_size - horizon + 1):\n",
                    "            self.X.append(data_array[i : i + window_size])\n",
                    "            if horizon == 1:\n",
                    "                self.y.append(data_array[i + window_size, target_col_idx])\n",
                    "            else:\n",
                    "                self.y.append(data_array[i + window_size : i + window_size + horizon, target_col_idx])\n",
                    "        self.X = torch.tensor(np.array(self.X), dtype=torch.float32)\n",
                    "        self.y = torch.tensor(np.array(self.y), dtype=torch.float32)\n",
                    "        if horizon == 1:\n",
                    "            self.y = self.y.unsqueeze(-1)\n",
                    "\n",
                    "    def __len__(self):\n",
                    "        return len(self.X)\n",
                    "\n",
                    "    def __getitem__(self, idx):\n",
                    "        return self.X[idx], self.y[idx]\n",
                    "\n",
                    "close_idx = feature_cols.index('Close')\n",
                    "train_ds = StockWindowDataset(train_scaled, window_size=60, horizon=1, target_col_idx=close_idx)\n",
                    "val_ds = StockWindowDataset(val_scaled, window_size=60, horizon=1, target_col_idx=close_idx)\n",
                    "test_ds = StockWindowDataset(test_scaled, window_size=60, horizon=1, target_col_idx=close_idx)\n",
                    "\n",
                    "train_loader = DataLoader(train_ds, batch_size=32, shuffle=True)\n",
                    "val_loader = DataLoader(val_ds, batch_size=32, shuffle=False)\n",
                    "test_loader = DataLoader(test_ds, batch_size=32, shuffle=False)\n",
                    "\n",
                    "print(f\"[DataLoader] Batch mẫu: X shape={next(iter(train_loader))[0].shape}, y shape={next(iter(train_loader))[1].shape}\")"
                ]
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "## PHẦN 5: XÂY DỰNG KIẾN TRÚC MÔ HÌNH (MODEL ZOO)\n",
                    "Đáp ứng đầy đủ: **Core LSTM**, **Compare CNN vs. LSTM**, **Multi-step Seq2Seq**, và **Proposed CNN-BiLSTM-Attention SOTA**."
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "# 1. Core Model: LSTM for Regression (Topic.png Core Requirement)\n",
                    "class VanillaLSTM(nn.Module):\n",
                    "    def __init__(self, input_dim, hidden_dim=64, num_layers=1, dropout=0.1):\n",
                    "        super().__init__()\n",
                    "        self.lstm = nn.LSTM(input_dim, hidden_dim, num_layers=num_layers, batch_first=True, dropout=dropout if num_layers > 1 else 0.0)\n",
                    "        self.fc = nn.Sequential(\n",
                    "            nn.Linear(hidden_dim, 32),\n",
                    "            nn.ReLU(),\n",
                    "            nn.Linear(32, 1)\n",
                    "        )\n",
                    "    def forward(self, x):\n",
                    "        out, (hn, _) = self.lstm(x)\n",
                    "        return self.fc(out[:, -1, :])\n",
                    "\n",
                    "# 2. Extension Model: 1D-CNN for Regression (Topic.png Compare CNN vs LSTM)\n",
                    "class VanillaCNN1D(nn.Module):\n",
                    "    def __init__(self, input_dim, num_filters=64, kernel_size=3):\n",
                    "        super().__init__()\n",
                    "        self.conv = nn.Sequential(\n",
                    "            nn.Conv1d(input_dim, num_filters, kernel_size=kernel_size, padding=kernel_size//2),\n",
                    "            nn.BatchNorm1d(num_filters),\n",
                    "            nn.ReLU(),\n",
                    "            nn.AdaptiveAvgPool1d(1)\n",
                    "        )\n",
                    "        self.fc = nn.Linear(num_filters, 1)\n",
                    "    def forward(self, x):\n",
                    "        # x: (B, L, D) -> (B, D, L)\n",
                    "        out = self.conv(x.permute(0, 2, 1))\n",
                    "        return self.fc(out.squeeze(-1))\n",
                    "\n",
                    "# 3. Proposed SOTA: CNN-BiLSTM-Self-Attention (Điểm Sáng NCKH)\n",
                    "class TemporalSelfAttention(nn.Module):\n",
                    "    def __init__(self, hidden_dim):\n",
                    "        super().__init__()\n",
                    "        self.attn = nn.Linear(hidden_dim, 1, bias=False)\n",
                    "    def forward(self, x):\n",
                    "        weights = torch.softmax(self.attn(x), dim=1)\n",
                    "        return (x * weights).sum(dim=1), weights\n",
                    "\n",
                    "class CNNBiLSTMAttention(nn.Module):\n",
                    "    def __init__(self, input_dim, cnn_filters=64, lstm_hidden=64, dropout=0.2):\n",
                    "        super().__init__()\n",
                    "        self.conv = nn.Sequential(\n",
                    "            nn.Conv1d(input_dim, cnn_filters, kernel_size=3, padding=1),\n",
                    "            nn.BatchNorm1d(cnn_filters),\n",
                    "            nn.SiLU(),\n",
                    "            nn.Dropout(dropout)\n",
                    "        )\n",
                    "        self.bilstm = nn.LSTM(cnn_filters, lstm_hidden, num_layers=2, batch_first=True, bidirectional=True, dropout=dropout)\n",
                    "        self.attention = TemporalSelfAttention(lstm_hidden * 2)\n",
                    "        self.head = nn.Sequential(\n",
                    "            nn.Linear(lstm_hidden * 2, 64),\n",
                    "            nn.SiLU(),\n",
                    "            nn.Dropout(dropout),\n",
                    "            nn.Linear(64, 1)\n",
                    "        )\n",
                    "    def forward(self, x):\n",
                    "        feat = self.conv(x.permute(0, 2, 1)).permute(0, 2, 1)\n",
                    "        lstm_out, _ = self.bilstm(feat)\n",
                    "        context, attn_w = self.attention(lstm_out)\n",
                    "        return self.head(context)\n",
                    "\n",
                    "print(\"[Models] Đã khởi tạo thành công 3 kiến trúc lõi: Vanilla LSTM, 1D-CNN, và SOTA CNN-BiLSTM-Attention!\")"
                ]
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "## PHẦN 6: HUẤN LUYỆN VỚI DIRECTIONAL PENALTY LOSS & EARLY STOPPING\n",
                    "Huấn luyện mô hình và theo dõi Loss chi tiết qua từng Epoch."
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "class DirectionalPenaltyLoss(nn.Module):\n",
                    "    def __init__(self, penalty_weight=0.5, close_idx=3):\n",
                    "        super().__init__()\n",
                    "        self.mse = nn.MSELoss()\n",
                    "        self.penalty_weight = penalty_weight\n",
                    "        self.close_idx = close_idx\n",
                    "    def forward(self, pred, target, x_seq):\n",
                    "        mse_loss = self.mse(pred, target)\n",
                    "        y_prev = x_seq[:, -1, self.close_idx].unsqueeze(-1)\n",
                    "        dir_pred = pred - y_prev\n",
                    "        dir_true = target - y_prev\n",
                    "        penalty = torch.relu(-dir_pred * dir_true).mean()\n",
                    "        return mse_loss + self.penalty_weight * penalty\n",
                    "\n",
                    "def train_model(model, train_loader, val_loader, epochs=25, lr=0.001):\n",
                    "    model = model.to(device)\n",
                    "    criterion = DirectionalPenaltyLoss(penalty_weight=0.5, close_idx=close_idx)\n",
                    "    optimizer = torch.optim.AdamW(model.parameters(), lr=lr, weight_decay=1e-4)\n",
                    "    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='min', factor=0.5, patience=5)\n",
                    "    \n",
                    "    history = {'train_loss': [], 'val_loss': []}\n",
                    "    best_val = float('inf')\n",
                    "    best_weights = None\n",
                    "    \n",
                    "    print(f\"\\n{'='*65}\\n BẮT ĐẦU HUẤN LUYỆN: {model.__class__.__name__}\\n{'='*65}\")\n",
                    "    for epoch in range(1, epochs + 1):\n",
                    "        model.train()\n",
                    "        t_loss = 0\n",
                    "        for bx, by in train_loader:\n",
                    "            bx, by = bx.to(device), by.to(device)\n",
                    "            optimizer.zero_grad()\n",
                    "            out = model(bx)\n",
                    "            loss = criterion(out, by, bx)\n",
                    "            loss.backward()\n",
                    "            optimizer.step()\n",
                    "            t_loss += loss.item() * len(bx)\n",
                    "        t_loss /= len(train_loader.dataset)\n",
                    "        \n",
                    "        model.eval()\n",
                    "        v_loss = 0\n",
                    "        with torch.no_grad():\n",
                    "            for bx, by in val_loader:\n",
                    "                bx, by = bx.to(device), by.to(device)\n",
                    "                out = model(bx)\n",
                    "                loss = criterion(out, by, bx)\n",
                    "                v_loss += loss.item() * len(bx)\n",
                    "        v_loss /= len(val_loader.dataset)\n",
                    "        \n",
                    "        history['train_loss'].append(t_loss)\n",
                    "        history['val_loss'].append(v_loss)\n",
                    "        scheduler.step(v_loss)\n",
                    "        \n",
                    "        star = \"⭐ [Best Checkpoint]\" if v_loss < best_val else \"\"\n",
                    "        if v_loss < best_val:\n",
                    "            best_val = v_loss\n",
                    "            best_weights = model.state_dict()\n",
                    "        if epoch % 5 == 0 or epoch == 1 or star:\n",
                    "            print(f\"Epoch [{epoch:02d}/{epochs:02d}] | Train Loss: {t_loss:.6f} | Val Loss: {v_loss:.6f} {star}\")\n",
                    "            \n",
                    "    model.load_state_dict(best_weights)\n",
                    "    return model, history\n",
                    "\n",
                    "# Huấn luyện 3 mô hình để so sánh\n",
                    "input_dim = len(feature_cols)\n",
                    "model_lstm, hist_lstm = train_model(VanillaLSTM(input_dim), train_loader, val_loader, epochs=25)\n",
                    "model_cnn, hist_cnn = train_model(VanillaCNN1D(input_dim), train_loader, val_loader, epochs=25)\n",
                    "model_sota, hist_sota = train_model(CNNBiLSTMAttention(input_dim), train_loader, val_loader, epochs=25)"
                ]
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "## PHẦN 7: SO SÁNH LOSS CURVE QUA CÁC EPOCH\n",
                    "Trực quan hóa đường cong mất mát của các mô hình qua từng Epoch."
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "plt.figure(figsize=(15, 4))\n",
                    "plt.subplot(1, 3, 1)\n",
                    "plt.plot(hist_lstm['train_loss'], label='Train Loss', color='#1f77b4')\n",
                    "plt.plot(hist_lstm['val_loss'], label='Val Loss', color='#ff7f0e', ls='--')\n",
                    "plt.title('Vanilla LSTM (Core Model)')\n",
                    "plt.xlabel('Epoch')\n",
                    "plt.ylabel('Loss')\n",
                    "plt.legend()\n",
                    "\n",
                    "plt.subplot(1, 3, 2)\n",
                    "plt.plot(hist_cnn['train_loss'], label='Train Loss', color='#2ca02c')\n",
                    "plt.plot(hist_cnn['val_loss'], label='Val Loss', color='#d62728', ls='--')\n",
                    "plt.title('1D-CNN (Extension Model)')\n",
                    "plt.xlabel('Epoch')\n",
                    "plt.ylabel('Loss')\n",
                    "plt.legend()\n",
                    "\n",
                    "plt.subplot(1, 3, 3)\n",
                    "plt.plot(hist_sota['train_loss'], label='Train Loss', color='#9467bd')\n",
                    "plt.plot(hist_sota['val_loss'], label='Val Loss', color='#8c564b', ls='--')\n",
                    "plt.title('Proposed CNN-BiLSTM-Attention (SOTA)')\n",
                    "plt.xlabel('Epoch')\n",
                    "plt.ylabel('Loss')\n",
                    "plt.legend()\n",
                    "\n",
                    "plt.tight_layout()\n",
                    "plt.show()"
                ]
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "## PHẦN 8: ĐÁNH GIÁ ĐA MÔ HÌNH & BACKTESTING ĐỊNH LƯỢNG\n",
                    "Khôi phục giá thực tế (Inverse Transform) và tính toán các chỉ số học máy (RMSE, MAE, MAPE, DA) cùng chỉ số tài chính thực tế (Sharpe, Max Drawdown, Total Return) sau khi trừ phí giao dịch 0.1% và trượt giá 0.05%."
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "def evaluate_predictions(model, test_loader, scaler, feature_cols, df_test_raw):\n",
                    "    model.eval()\n",
                    "    preds_scaled, trues_scaled = [], []\n",
                    "    with torch.no_grad():\n",
                    "        for bx, by in test_loader:\n",
                    "            bx = bx.to(device)\n",
                    "            out = model(bx)\n",
                    "            preds_scaled.append(out.cpu().numpy())\n",
                    "            trues_scaled.append(by.numpy())\n",
                    "    preds_scaled = np.vstack(preds_scaled)\n",
                    "    trues_scaled = np.vstack(trues_scaled)\n",
                    "    \n",
                    "    # Inverse transform về giá USD thực tế\n",
                    "    close_idx = feature_cols.index('Close')\n",
                    "    dummy_p = np.zeros((len(preds_scaled), len(feature_cols)))\n",
                    "    dummy_t = np.zeros((len(trues_scaled), len(feature_cols)))\n",
                    "    dummy_p[:, close_idx] = preds_scaled.ravel()\n",
                    "    dummy_t[:, close_idx] = trues_scaled.ravel()\n",
                    "    \n",
                    "    preds_real = scaler.inverse_transform(dummy_p)[:, close_idx]\n",
                    "    trues_real = scaler.inverse_transform(dummy_t)[:, close_idx]\n",
                    "    \n",
                    "    # ML Metrics\n",
                    "    rmse = np.sqrt(np.mean((preds_real - trues_real) ** 2))\n",
                    "    mae = np.mean(np.abs(preds_real - trues_real))\n",
                    "    mape = np.mean(np.abs((preds_real - trues_real) / trues_real)) * 100\n",
                    "    \n",
                    "    # Directional Accuracy\n",
                    "    prev_real = trues_real[:-1]\n",
                    "    da = np.mean((preds_real[1:] - prev_real > 0) == (trues_real[1:] - prev_real > 0)) * 100\n",
                    "    \n",
                    "    # Financial Backtest (Khấu trừ phí 0.1% + trượt giá 0.05%)\n",
                    "    signals = np.where(preds_real[1:] > prev_real, 1, 0) # 1: Long, 0: Cash\n",
                    "    pct_change = (trues_real[1:] - prev_real) / prev_real\n",
                    "    trades = np.diff(np.insert(signals, 0, 0)) != 0\n",
                    "    cost = trades * (0.001 + 0.0005)\n",
                    "    strategy_ret = signals * pct_change - cost\n",
                    "    \n",
                    "    total_return = (np.prod(1 + strategy_ret) - 1) * 100\n",
                    "    sharpe = (np.mean(strategy_ret) / (np.std(strategy_ret) + 1e-9)) * np.sqrt(252)\n",
                    "    cum_ret = np.cumprod(1 + strategy_ret)\n",
                    "    peaks = np.maximum.accumulate(cum_ret)\n",
                    "    max_dd = np.max((peaks - cum_ret) / peaks) * 100\n",
                    "    \n",
                    "    return {\n",
                    "        'RMSE ($)': round(rmse, 2),\n",
                    "        'MAE ($)': round(mae, 2),\n",
                    "        'MAPE (%)': round(mape, 2),\n",
                    "        'DA (%)': round(da, 2),\n",
                    "        'Total Return (%)': round(total_return, 2),\n",
                    "        'Sharpe Ratio': round(sharpe, 2),\n",
                    "        'Max Drawdown (%)': round(max_dd, 2)\n",
                    "    }, preds_real, trues_real\n",
                    "\n",
                    "res_lstm, p_lstm, t_real = evaluate_predictions(model_lstm, test_loader, scaler, feature_cols, df_test)\n",
                    "res_cnn, p_cnn, _ = evaluate_predictions(model_cnn, test_loader, scaler, feature_cols, df_test)\n",
                    "res_sota, p_sota, _ = evaluate_predictions(model_sota, test_loader, scaler, feature_cols, df_test)\n",
                    "\n",
                    "df_benchmark = pd.DataFrame([\n",
                    "    {'Model': 'Vanilla LSTM (Core)', **res_lstm},\n",
                    "    {'Model': 'Vanilla 1D-CNN (Extension: CNN vs LSTM)', **res_cnn},\n",
                    "    {'Model': 'Proposed CNN-BiLSTM-Attention (SOTA)', **res_sota}\n",
                    "])\n",
                    "\n",
                    "print(\"\\n\" + \"=\"*80)\n",
                    "print(\"         BẢNG KẾT QUẢ SO SÁNH CHUẨN NCKH (ABLATION BENCHMARK)\")\n",
                    "print(\"=\"*80)\n",
                    "display(df_benchmark)"
                ]
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "## PHẦN 9: TRỰC QUAN HÓA KẾT QUẢ DỰ BÁO VS THỰC TẾ TRÊN TẬP TEST (2024)"
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "test_dates = df_test['Date'].iloc[60:].reset_index(drop=True)\n",
                    "\n",
                    "plt.figure(figsize=(15, 6))\n",
                    "plt.plot(test_dates, t_real, label='Giá Thực Tế (Ground Truth)', color='black', lw=2.2)\n",
                    "plt.plot(test_dates, p_lstm, label='Dự Báo: Vanilla LSTM (Core)', color='#1f77b4', alpha=0.85, lw=1.5)\n",
                    "plt.plot(test_dates, p_cnn, label='Dự Báo: 1D-CNN (Extension)', color='#2ca02c', alpha=0.85, lw=1.5)\n",
                    "plt.plot(test_dates, p_sota, label='Dự Báo: SOTA CNN-BiLSTM-Attention', color='#d62728', lw=1.8)\n",
                    "plt.title(f'So Sánh Dự Báo Giá Đóng Cửa {ticker} Trên Tập Test (Năm 2024)', fontsize=14, fontweight='bold')\n",
                    "plt.xlabel('Thời gian')\n",
                    "plt.ylabel('Giá Cổ Phiếu ($)')\n",
                    "plt.legend(loc='upper left')\n",
                    "plt.tight_layout()\n",
                    "plt.show()"
                ]
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "## PHẦN 10: DEMO DỰ BÁO THỜI GIAN THỰC (REAL-TIME NEXT-DAY PREDICTION)\n",
                    "Tự động tải 60 phiên giao dịch gần nhất từ Yahoo Finance tính đến hôm nay và dự báo giá ngày tiếp theo cùng khuyến nghị định lượng."
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "print(f\"[Live Inference] Đang tải dữ liệu thời gian thực {ticker} từ Yahoo Finance...\")\n",
                    "df_live = yf.download(ticker, period='6mo', progress=False)\n",
                    "if isinstance(df_live.columns, pd.MultiIndex):\n",
                    "    df_live.columns = df_live.columns.get_level_values(0)\n",
                    "df_live.reset_index(inplace=True)\n",
                    "df_live['Date'] = pd.to_datetime(df_live['Date'])\n",
                    "\n",
                    "df_live_feat = add_technical_indicators(df_live)\n",
                    "live_scaled = scaler.transform(df_live_feat[feature_cols])[-60:]\n",
                    "live_tensor = torch.tensor(live_scaled, dtype=torch.float32).unsqueeze(0).to(device)\n",
                    "\n",
                    "model_sota.eval()\n",
                    "with torch.no_grad():\n",
                    "    pred_live_scaled = model_sota(live_tensor).cpu().numpy()\n",
                    "\n",
                    "dummy_live = np.zeros((1, len(feature_cols)))\n",
                    "dummy_live[0, close_idx] = pred_live_scaled[0, 0]\n",
                    "pred_live_price = scaler.inverse_transform(dummy_live)[0, close_idx]\n",
                    "\n",
                    "last_date = df_live_feat['Date'].iloc[-1].strftime('%Y-%m-%d')\n",
                    "last_price = df_live_feat['Close'].iloc[-1]\n",
                    "expected_return = ((pred_live_price - last_price) / last_price) * 100\n",
                    "\n",
                    "if expected_return > 1.0:\n",
                    "    signal = \"🟢 MUA (BUY) - Xu hướng tăng mạnh\"\n",
                    "elif expected_return < -1.0:\n",
                    "    signal = \"🔴 BÁN (SELL) - Xu hướng giảm mạnh\"\n",
                    "else:\n",
                    "    signal = \"🟡 GIỮ / QUAN SÁT (HOLD) - Xu hướng đi ngang\"\n",
                    "\n",
                    "print(\"=\"*65)\n",
                    "print(f\"      KẾT QUẢ DỰ BÁO THỜI GIAN THỰC CHO MÃ: {ticker}\")\n",
                    "print(\"=\"*65)\n",
                    "print(f\"Phiên giao dịch gần nhất ({last_date}): ${last_price:.2f}\")\n",
                    "print(f\"Giá dự báo phiên kế tiếp (Next-Day):     ${pred_live_price:.2f}\")\n",
                    "print(f\"Biến động kỳ vọng:                      {expected_return:+.2f}%\")\n",
                    "print(f\"Khuyến nghị định lượng:                 {signal}\")\n",
                    "print(\"=\"*65)"
                ]
            }
        ],
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3 (stock_env)",
                "language": "python",
                "name": "python3"
            },
            "language_info": {
                "codemirror_mode": {
                    "name": "ipython",
                    "version": 3
                },
                "file_extension": ".py",
                "mimetype": "text/x-python",
                "name": "python",
                "nbconvert_exporter": "python",
                "pygments_lexer": "ipython3",
                "version": "3.13.0"
            }
        },
        "nbformat": 4,
        "nbformat_minor": 4
    }
    
    with open("Stock_Forecasting_Topic4_Demo.ipynb", "w", encoding="utf-8") as f:
        json.dump(notebook, f, indent=2, ensure_ascii=False)
    print("[Thành công] Đã tạo file notebook: Stock_Forecasting_Topic4_Demo.ipynb")

if __name__ == "__main__":
    create_demo_notebook()
